<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AutoCore.Database\AutoCore.Database.csproj" />
    <ProjectReference Include="..\AutoCore.Game\AutoCore.Game.csproj" />
    <ProjectReference Include="..\AutoCore.Utils\AutoCore.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.17.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
