<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AutoCore.Sim.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoCore.Game\AutoCore.Game.csproj" />
    <ProjectReference Include="..\AutoCore.Utils\AutoCore.Utils.csproj" />
  </ItemGroup>

</Project>
